Repository collaborationFactory/cplace-npm-tools, pull requests merged in 2023-02, with the labels that each got.

#117 PFM-ISSUE-11909: fix empty lines when migrating artifact groups
  package-lock.json
  package.json
  src/commands/repos/AbstractReposCommand.ts
  src/commands/repos/MigrateArtifactGroup.ts
Labels: bug, PR: Needs Review

#103 PFM-TASK-3040: Adjust cplace cli to Node version 18.11.0
  .github/workflows/continuous-integration.yml
  .github/workflows/npm-release.yml
  .nvmrc
  .tool-versions
  package-lock.json
  package.json
Labels: PR: Ready to Merge

#120 PFM-ISSUE-12095: Update merge skeleton command with version 9
  src/commands/repos/MergeSkeleton.ts
Labels: PR: Needs Review
